# Generated by Django 3.0 on 2019-12-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='telefone',
        ),
    ]
