# Generated by Django 3.0.2 on 2020-02-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_auto_20191210_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
    ]
