# Generated by Django 3.0.2 on 2020-02-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_auto_20200214_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campus'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Professores'},
        ),
    ]
