# Generated by Django 3.0 on 2019-12-10 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('ultimoNome', models.CharField(max_length=20, verbose_name='Último nome')),
                ('matricula', models.CharField(max_length=12, unique=True, verbose_name='Matrícula')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Campus')),
                ('sigla', models.CharField(max_length=30, verbose_name='Sigla')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Curso')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=100, verbose_name='descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('autor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repositorio.Autor')),
            ],
            bases=('repositorio.autor',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('autor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repositorio.Autor')),
            ],
            bases=('repositorio.autor',),
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('palavraChave', models.CharField(max_length=200, verbose_name='Palavra Chave')),
                ('abstract', models.TextField(verbose_name='Abstract')),
                ('dataPublicacao', models.DateField()),
                ('pdf', models.FileField(upload_to='', verbose_name='PDF')),
                ('autor', models.ManyToManyField(to='repositorio.Autor')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Campus')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Curso')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.TipoTrabalho')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repositorio.Professor')),
            ],
        ),
    ]
